#!/usr/bin/env bash
set -euo pipefail

OMEGA_URL="${OMEGA_URL:-http://localhost:8090}"
IDENTITY_BIN="${IDENTITY_BIN:-}"

echo "=== Seeding United States of Omega ==="
echo "Target: $OMEGA_URL"
echo

# Build identity tool if not provided
if [ -z "$IDENTITY_BIN" ]; then
  echo "Building identity tool..."
  IDENTITY_BIN=$(mktemp)
  (cd "$(dirname "$0")/../src/backend" && go build -o "$IDENTITY_BIN" ./cmd/identity/) 2>/dev/null
  trap "rm -f $IDENTITY_BIN" EXIT
fi

# Create government
GOV=$(curl -sS -X POST "$OMEGA_URL/api/governments" \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "United States of Omega",
    "config": {
      "initial_balance": 10000,
      "interest_rate": 0.02,
      "mint_per_tick": 100,
      "transfer_tax": 0.03,
      "open_membership": true,
      "max_citizens": 0,
      "governor_mode": "agent"
    }
  }')
GOV_ID=$(echo "$GOV" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "Government created: $GOV_ID"
echo

# Generate keys and register an agent
register_agent() {
  local name="$1" agent_dir="$2" model="$3"
  local key_dir="$agent_dir/keys"
  mkdir -p "$key_dir"

  # Generate key pair
  OMEGA_KEY_DIR="$key_dir" "$IDENTITY_BIN" generate > /dev/null 2>&1
  local pubkey=$(cat "$key_dir/omega.pub")

  local soul_md=""
  if [ -f "$agent_dir/SOUL.md" ]; then
    soul_md=$(cat "$agent_dir/SOUL.md" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" | sed 's/^"//;s/"$//')
  fi

  local result
  result=$(curl -sS -X POST "$OMEGA_URL/api/governments/$GOV_ID/registry/register" \
    -H 'Content-Type: application/json' \
    -d "{\"name\": \"$name\", \"public_key\": \"$pubkey\", \"soul_md\": \"$soul_md\", \"model\": \"$model\"}")
  local id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
  echo "$id $pubkey"
}

AGENTS_DIR="$(dirname "$0")/../agents"

echo "Registering agents..."

read PRES_ID PRES_PUB <<< $(register_agent "President" "$AGENTS_DIR/president" "minimax/minimax-m2.7")
echo "  President:    $PRES_ID"

read SEN1_ID SEN1_PUB <<< $(register_agent "Senator One (Speaker)" "$AGENTS_DIR/senator-1" "minimax/minimax-m2.7")
echo "  Senator 1:    $SEN1_ID"

read SEN2_ID SEN2_PUB <<< $(register_agent "Senator Two (Finance)" "$AGENTS_DIR/senator-2" "minimax/minimax-m2.7")
echo "  Senator 2:    $SEN2_ID"

read SEN3_ID SEN3_PUB <<< $(register_agent "Senator Three (Foreign)" "$AGENTS_DIR/senator-3" "minimax/minimax-m2.7")
echo "  Senator 3:    $SEN3_ID"

read FED_ID FED_PUB <<< $(register_agent "Fed Chair" "$AGENTS_DIR/fed-chair" "minimax/minimax-m2.7")
echo "  Fed Chair:    $FED_ID"

echo

# Create firms using signed requests
sign_and_post() {
  local key_dir="$1" path="$2" body="$3"
  local auth=$(OMEGA_KEY_DIR="$key_dir" "$IDENTITY_BIN" sign POST "$path")
  curl -sS -X POST "$OMEGA_URL$path" \
    -H "Authorization: $auth" \
    -H 'Content-Type: application/json' \
    -d "$body"
}

echo "Creating branches..."
EXEC_FIRM=$(sign_and_post "$AGENTS_DIR/president/keys" "/api/governments/$GOV_ID/registry/firms" '{"name":"Executive Branch"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "  Executive Branch: $EXEC_FIRM"

CONG_FIRM=$(sign_and_post "$AGENTS_DIR/senator-1/keys" "/api/governments/$GOV_ID/registry/firms" '{"name":"Congress"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "  Congress:         $CONG_FIRM"

FED_FIRM=$(sign_and_post "$AGENTS_DIR/fed-chair/keys" "/api/governments/$GOV_ID/registry/firms" '{"name":"Federal Reserve"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "  Federal Reserve:  $FED_FIRM"

echo

# Write .env file
cat > .env <<EOF
# Generated by seed.sh — $(date -Iseconds)
OMEGA_GOV_ID=$GOV_ID

# Agent IDs
PRESIDENT_ID=$PRES_ID
SENATOR1_ID=$SEN1_ID
SENATOR2_ID=$SEN2_ID
SENATOR3_ID=$SEN3_ID
FEDCHAIR_ID=$FED_ID

# Firm IDs
EXECUTIVE_FIRM_ID=$EXEC_FIRM
CONGRESS_FIRM_ID=$CONG_FIRM
FEDERAL_RESERVE_FIRM_ID=$FED_FIRM

# Set your LLM provider key
# OPENROUTER_API_KEY=your-key-here
EOF

# Preserve existing OPENROUTER_API_KEY if set
if [ -n "${OPENROUTER_API_KEY:-}" ]; then
  echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY" >> .env
fi

echo "=== Done ==="
echo
echo ".env file written."
echo "Key pairs stored in agents/*/keys/ (private keys — do not commit!)"
echo
echo "Government: $GOV_ID"
echo "Citizens:   5 (President, 3 Senators, Fed Chair)"
echo "Firms:      3 (Executive, Congress, Federal Reserve)"
echo "Balance:    10,000 per citizen"
echo
echo "Chat with an agent:"
echo "  cd src/backend && go run ./cmd/chat -agent ../../agents/president"
