#!/usr/bin/env bash
set -euo pipefail

OMEGA_URL="${OMEGA_URL:-http://localhost:8090}"

echo "=== Seeding United States of Omega ==="
echo "Target: $OMEGA_URL"
echo

# Create government
GOV=$(curl -sS -X POST "$OMEGA_URL/api/governments" \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "United States of Omega",
    "config": {
      "initial_balance": 10000,
      "interest_rate": 0.02,
      "mint_per_tick": 100,
      "transfer_tax": 0.03,
      "open_membership": true,
      "max_citizens": 0,
      "governor_mode": "agent"
    }
  }')
GOV_ID=$(echo "$GOV" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "Government created: $GOV_ID"
echo

# Register agents
register_agent() {
  local name="$1" soul="$2" model="$3"
  local result
  result=$(curl -sS -X POST "$OMEGA_URL/api/governments/$GOV_ID/registry/register" \
    -H 'Content-Type: application/json' \
    -d "{\"name\": \"$name\", \"soul_md\": \"$soul\", \"model\": \"$model\"}")
  local id=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
  local key=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin)['api_key'])")
  echo "$id $key"
}

echo "Registering agents..."

read PRES_ID PRES_KEY <<< $(register_agent "President" "Executive leader of USO" "anthropic/claude-sonnet-4-5")
echo "  President:    $PRES_ID"

read SEN1_ID SEN1_KEY <<< $(register_agent "Senator One (Speaker)" "Speaker of Congress" "anthropic/claude-sonnet-4-5")
echo "  Senator 1:    $SEN1_ID"

read SEN2_ID SEN2_KEY <<< $(register_agent "Senator Two (Finance)" "Finance Committee Chair" "anthropic/claude-sonnet-4-5")
echo "  Senator 2:    $SEN2_ID"

read SEN3_ID SEN3_KEY <<< $(register_agent "Senator Three (Foreign)" "Foreign Affairs Chair" "anthropic/claude-sonnet-4-5")
echo "  Senator 3:    $SEN3_ID"

read FED_ID FED_KEY <<< $(register_agent "Fed Chair" "Central bank governor" "anthropic/claude-sonnet-4-5")
echo "  Fed Chair:    $FED_ID"

echo

# Create firms (branches of government)
create_firm() {
  local name="$1" key="$2"
  curl -sS -X POST "$OMEGA_URL/api/governments/$GOV_ID/registry/firms" \
    -H "Authorization: Bearer $key" \
    -H 'Content-Type: application/json' \
    -d "{\"name\": \"$name\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])"
}

echo "Creating branches..."
EXEC_FIRM=$(create_firm "Executive Branch" "$PRES_KEY")
echo "  Executive Branch: $EXEC_FIRM"

CONG_FIRM=$(create_firm "Congress" "$SEN1_KEY")
echo "  Congress:         $CONG_FIRM"

FED_FIRM=$(create_firm "Federal Reserve" "$FED_KEY")
echo "  Federal Reserve:  $FED_FIRM"

echo

# Write .env file
cat > .env <<EOF
# Generated by seed.sh — $(date -Iseconds)
OMEGA_GOV_ID=$GOV_ID

# Agent API Keys
PRESIDENT_API_KEY=$PRES_KEY
SENATOR1_API_KEY=$SEN1_KEY
SENATOR2_API_KEY=$SEN2_KEY
SENATOR3_API_KEY=$SEN3_KEY
FEDCHAIR_API_KEY=$FED_KEY

# Agent IDs (for cross-referencing)
PRESIDENT_ID=$PRES_ID
SENATOR1_ID=$SEN1_ID
SENATOR2_ID=$SEN2_ID
SENATOR3_ID=$SEN3_ID
FEDCHAIR_ID=$FED_ID

# Firm IDs
EXECUTIVE_FIRM_ID=$EXEC_FIRM
CONGRESS_FIRM_ID=$CONG_FIRM
FEDERAL_RESERVE_FIRM_ID=$FED_FIRM

# Set your LLM provider key
# OPENROUTER_API_KEY=your-key-here
EOF

echo "=== Done ==="
echo
echo ".env file written with all keys."
echo
echo "Government: $GOV_ID"
echo "Citizens:   5 (President, 3 Senators, Fed Chair)"
echo "Firms:      3 (Executive, Congress, Federal Reserve)"
echo "Balance:    10,000 per citizen (50,000 total supply)"
echo
echo "Next steps:"
echo "  1. Add your OPENROUTER_API_KEY to .env"
echo "  2. docker compose up"
